backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "content/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "https://thegaymoviecatalog.netlify.com/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "Blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/Blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "date", name: "date", widget: "datetime", required: false}
      - {label: "Post Type", name: "post_type", default: "text", required: false}
      - {label: "Image Upload", name: "upload_sign", widget: "imagetext", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "Gay Movie" # Used in routes, e.g., /admin/collections/blog
    label: "Gay Movie" # Used in the UI
    folder: "content/Gay Movie" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Original Title", name: "original", widget: "string", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Country", name: "country", widget: "string", required: false}
      - {label: "Featuring", name: "featuring", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Image Upload", name: "upload_sign", widget: "imagetext", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "string", required: false}
      - {label: "Video", name: "youtube", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "Gay Short Movie" # Used in routes, e.g., /admin/collections/blog
    label: "Gay Short Movie" # Used in the UI
    folder: "content/Gay Short Movie" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Original Title", name: "original", widget: "text", required: false}
      - {label: Year, name: year, widget: string, required: false}
      - {label: "Country", name: "country", widget: "text", required: false}
      - {label: "Featuring", name: "featuring", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Image Upload", name: "upload_sign", widget: "image", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "text", required: false}
      - {label: "Video", name: "youtube", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}